### ISSUE TITLE
libmultipath does not compile against glibc 2.34

### ISSUE THREAD

**Issue by Uglymotha** [opensvc/multipath-tools#10]
From glibc 2.34 changelog:
* When _DYNAMIC_STACK_SIZE_SOURCE or _GNU_SOURCE are defined,
  PTHREAD_STACK_MIN is no longer constant and is redefined to
  sysconf(_SC_THREAD_STACK_MIN).  This supports dynamic sized register
  sets for modern architectural features like Arm SVE.

Result is a type mismatch error in libmultipath/util.c,  unsigned long int (size_t) vs unsigned int on line 226:
	if (stacksize < PTHREAD_STACK_MIN)

changing stacksize to be long int fixes the issue, but not sure if thats a desirable solution.

**Comment by bmarzins** [comment]
There's a patch posted for this here:
https://listman.redhat.com/archives/dm-devel/2021-July/msg00159.html

As part of this patchset:
https://listman.redhat.com/archives/dm-devel/2021-July/msg00157.html

**Comment by mwilck** [comment]
Addressed by #13.

**Comment by mwilck** [comment]
Fixed by #13
