### ISSUE TITLE
enable_group Segmentation fault

### ISSUE THREAD

**Issue by linzhanglong** [opensvc/multipath-tools#105]
Hello.  In the do_check_path function, the following code:
```
if (pp->mpp->synced_count == 0) {  
    do_sync_mpp(vecs, pp->mpp);  
    /* if update_multipath_strings orphaned the path, quit early */  
    if (!pp->mpp)  
        return CHECK_PATH_SKIPPED;  
}
```

should be changed to ?
```
if (pp->mpp->synced_count == 0) {  
    do_sync_mpp(vecs, pp->mpp);  
    /* if update_multipath_strings orphaned the path, quit early */  
    if (!pp->mpp || pp->mpp->need_reload)  <--------------------------------modify  
        return CHECK_PATH_SKIPPED;  
}
```

Otherwise, the subsequent code in the enable_group function may access the pgindex array out of bounds:
```
static void
enable_group(struct path * pp)
{
    struct pathgroup * pgp;

    if (!pp->mpp->pg || !pp->pgindex)
        return;

    pgp = VECTOR_SLOT(pp->mpp->pg, pp->pgindex - 1); <-------------------------------------- here

    if (pgp->status == PGSTATE_DISABLED) {
        condlog(2, "%s: enable group #%i", pp->mpp->alias, pp->pgindex);
        dm_enablegroup(pp->mpp->alias, pp->pgindex);
    }
}
```

**Comment by mwilck** [comment]
Thanks for the report.

1. Which multipath-tools version are you using? 
1. Have you observed a multipathd crash? If yes, 
   - can you share the multipathd logs preceding the crash with us, please? 
   - Can you reproduce the crash?

I've reviewed the code, and while it's true that `update_pathvec_from_dm()` may modify `pp->mpp`, I am not sure if your fix is correct. The problem is our lax handling of `pp->pgindex` in general. I'm going to send a patch to `dm-devel`.

**Comment by linzhanglong** [comment]
Hello, I'm not at the office right now, I will provide the information later. This issue occurs with  very low probability in a   Active-Standby mode when you modify the LUN ID and then change it back. When multipathd detects a change in pp wwid, update_pathvec_from_dm will remove the path and also remove the empty pg, which can lead to this issue.

**Comment by mwilck** [comment]
I've sent a patch to dm-devel@lists.linux.dev. Subject is "libmultipath: fix handling of pp->pgindex". You can inspect it [here](https://github.com/opensvc/multipath-tools/commit/ec83f4bb309df382894c449d1f3024c8d65405a8), too.

**Comment by linzhanglong** [comment]
Hello. Could the following code in the update_pathvec_from_dm function also lead to remove paths and empty path groups?
```
/* If this fails, the device is not in sysfs */
pp->udev = get_udev_device(pp->dev_t, DEV_DEVT);

if (!pp->udev) {
    condlog(2, "%s: discarding non-existing path %s",
        mpp->alias, pp->dev_t);
    vector_del_slot(pgp->paths, j--);
    free_path(pp);
    must_reload = true;
    continue;
}
```

**Comment by linzhanglong** [comment]
Hello. Could the following code in the update_pathvec_from_dm function also lead to remove paths and empty path groups? It could cause the same issue ?
```
/* If this fails, the device is not in sysfs */
pp->udev = get_udev_device(pp->dev_t, DEV_DEVT);

if (!pp->udev) {
    condlog(2, "%s: discarding non-existing path %s",
        mpp->alias, pp->dev_t);
    vector_del_slot(pgp->paths, j--);
    free_path(pp);
    must_reload = true;
    continue;
}
```



the logs related to my previous question:
2024-11-11 17:49:31.653829 err [multipathd:] 36b46e0810052656500146efa00000005: path 66:1312 WWID 36b46e0810052656512345678000103e8 doesn't match, removing from map
2024-11-11 17:49:31.653846 notice [multipathd:] 36b46e0810052656500146efa00000005: removing empty pathgroup 5
2024-11-11 17:49:31.653853 warning [multipathd:] 36b46e0810052656500146efa00000005: sdbbk - rdac checker reports path is up
2024-11-11 17:49:31.653860 notice [multipathd:] 128:1376: reinstated
2024-11-11 17:49:31.653867 notice [multipathd:] 36b46e0810052656500146efa00000005: remaining active paths: 6
2024-11-11 17:49:47.588389 notice [multipathd:] --------start up--------

**Comment by mwilck** [comment]
Yes. @bmarzins pointed out the same thing on dm-devel.

I have posted another patch series to the dm-devel mailing list ("[PATCH v2 0/8] multipath-tools fixes") with an updated fix that should cover your case.

The set is also on my [tip branch](https://github.com/openSUSE/multipath-tools/tree/tip).

**Comment by mwilck** [comment]
> 2024-11-11 17:49:31.653829 err [multipathd:] 36b46e0810052656500146efa00000005: path 66:1312 WWID 36b46e0810052656512345678000103e8 doesn't match, removing from map

You (or we) should investigate how it comes to pass that this path with a wrong WWID is in this map. The log history should provide some clue about it.

multipathd tries to work around this, but it represents some rather evil problem that has probably external reasons (a path has changed its WWID without being deleted and re-added).

**Comment by linzhanglong** [comment]
> You (or we) should investigate how it comes to pass that this path with a wrong WWID is in this map. The log history should provide some clue about it.
> 
> multipathd tries to work around this, but it represents some rather evil problem that has probably external reasons (a path has changed its WWID without being deleted and re-added).

Okay.
When modify the LUN ID or unmap this LUN  on the storage side , the WWID of this LUN will change when viewed from the host side.

**Comment by mwilck** [comment]
> When modify the LUN ID or unmap this LUN on the storage side , the WWID of this LUN will change when viewed from the host side.

And there are no uevents on the host when this happens?

**Comment by linzhanglong** [comment]
> > When modify the LUN ID or unmap this LUN on the storage side , the WWID of this LUN will change when viewed from the host side.
> 
> And there are no uevents on the host when this happens?

Yes, the storage LUN is not mounted. I modified the LUN ID on the storage side, and then executed the command " udevadm monitor --kernel --property",  but there were no uevent events. 
The storage is HUAWEI XSG1.

**Comment by mwilck** [comment]
Are there any kernel messages about changed LUNs or the like?

It is highly dangerous to swap a SCSI device in this way while a host is accessing it. It it isn't mounted, there's no immediate threat of data corruption, but still, I would strongly discourage doing it.

**Comment by linzhanglong** [comment]
Yes, these tests were conducted while I was analyzing that core.
If the kernel issues the scsi command to the storage while the LUN ID is being modified, the kernel can receive the return code from the storage and detect that the LUN data has changed. In this scenario, a uevent will be triggered, but this depends on probability.

```
static void scsi_report_sense(struct scsi_device *sdev,
			      struct scsi_sense_hdr *sshdr)
{
	enum scsi_device_event evt_type = SDEV_EVT_MAXBITS;	/* i.e. none */

	if (sshdr->sense_key == UNIT_ATTENTION) {
		if (sshdr->asc == 0x3f && sshdr->ascq == 0x03) {
			evt_type = SDEV_EVT_INQUIRY_CHANGE_REPORTED;
			sdev_printk(KERN_WARNING, sdev,
				    "Inquiry data has changed");
		} else if (sshdr->asc == 0x3f && sshdr->ascq == 0x0e) {
			evt_type = SDEV_EVT_LUN_CHANGE_REPORTED;
			scsi_report_lun_change(sdev);  <---------------------------------------------------------- here
			sdev_printk(KERN_WARNING, sdev,
				    "Warning! Received an indication that the "
				    "LUN assignments on this target have "
				    "changed. The Linux SCSI layer does not "
				    "automatically remap LUN assignments.\n");
		} else if (sshdr->asc == 0x3f)
			sdev_printk(KERN_WARNING, sdev,
				    "Warning! Received an indication that the "
				    "operating parameters on this target have "
				    "changed. The Linux SCSI layer does not "
				    "automatically adjust these parameters.\n");

		if (sshdr->asc == 0x38 && sshdr->ascq == 0x07) {
			evt_type = SDEV_EVT_SOFT_THRESHOLD_REACHED_REPORTED;
			sdev_printk(KERN_WARNING, sdev,
				    "Warning! Received an indication that the "
				    "LUN reached a thin provisioning soft "
				    "threshold.\n");
		}

		if (sshdr->asc == 0x29) {
			scsi_disk_reset_handler(sdev);
			evt_type = SDEV_EVT_POWER_ON_RESET_OCCURRED;
			sdev_printk(KERN_WARNING, sdev,
				    "Power-on or device reset occurred\n");
		}

		if (sshdr->asc == 0x2a && sshdr->ascq == 0x01) {
			evt_type = SDEV_EVT_MODE_PARAMETER_CHANGE_REPORTED;
			sdev_printk(KERN_WARNING, sdev,
				    "Mode parameters changed");
		} else if (sshdr->asc == 0x2a && sshdr->ascq == 0x06) {
			evt_type = SDEV_EVT_ALUA_STATE_CHANGE_REPORTED;
			sdev_printk(KERN_WARNING, sdev,
				    "Asymmetric access state changed");
		} else if (sshdr->asc == 0x2a && sshdr->ascq == 0x09) {
			evt_type = SDEV_EVT_CAPACITY_CHANGE_REPORTED;
			sdev_printk(KERN_WARNING, sdev,
				    "Capacity data has changed");
		} else if (sshdr->asc == 0x2a)
			sdev_printk(KERN_WARNING, sdev,
				    "Parameters changed");
	}

	if (evt_type != SDEV_EVT_MAXBITS) {
		set_bit(evt_type, sdev->pending_events);
		schedule_work(&sdev->event_work);
	}
}
```

**Comment by mwilck** [comment]
Ok, I understand.

Do you still observe the crash with the current patch set?

**Comment by linzhanglong** [comment]
> Ok, I understand.
> 
> Do you still observe the crash with the current patch set?

I am testing. I have a small question: if this issue occurs and the pgindex is set to invalid, where can we ensure that the reload map will be triggered?

**Comment by mwilck** [comment]
> I have a small question: if this issue occurs and the pgindex is set to invalid, where can we ensure that the reload map will be triggered?

That question isn't small. We currently don't. It's a subtle matter because we must avoid spurious map reloads, and endless reload loops. The difficult part is where we can safely reload the map. I've double-checked, and I think that `do_sync_mpp()` is the correct place to attempt a reload like this.

I have just pushed another commit (ab60145) [to my "tip" branch](https://github.com/openSUSE/multipath-tools/tree/tip). I'm curious to see if it works for your case (i.e. causes a map reload for the broken map).

@bmarzins, your opinion about that commit would also be highly appreciated, as you've made lots of changes around the checkerloop recently.

**Comment by mwilck** [comment]
Note that the fact that multipathd receives no notifications about SCSI Unit Attention (UA)events is a long-standing problem. We have missing links un multiple levels here. 
We might get a UA, but not necessarily on the path that had changed, it can be some other path device belonging to the same SCSI target. Even if the UA is received, it doesn't trigger a target rescan by the kernel, and even if the rescan is done, it doesn't trigger a block-level uevent, even if the device ID changes.

**Comment by mwilck** [comment]
@linzhanglong, can you describe your test procedure in detail? You change a LUN assignment on the storage side, and then what do you do on the host side?

**Comment by linzhanglong** [comment]
> Do you observe kernel messages like this?
> 
> ```
> LUN assignments on this target have changed. The Linux SCSI layer does not automatically remap LUN assignments.
> ```
> 
> Also, could you run `udevadm monitor -k -p -s scsi` when the LUN assignment changes, and see if the kernel sends any notification about the changed LUN assignments to user space?

Hello, I just tested a single LUN, and the reason I previously mentioned not receiving the uevent event was because I was filtering with sdx. In fact, the uevent events were received, and they are as follows:
```
KERNEL[22778.730765] change   /devices/pci0000:3a/0000:3a:00.0/0000:3b:00.1/host15/rport-15:0-13/target15:0:7/15:0:7:1 (scsi)
ACTION=change
DEVPATH=/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.1/host15/rport-15:0-13/target15:0:7/15:0:7:1
DEVTYPE=scsi_device
DRIVER=sd
MODALIAS=scsi:t-0x00
SDEV_UA=REPORTED_LUNS_DATA_HAS_CHANGED
SEQNUM=18718
SUBSYSTEM=scsi
UDEV_LOG=6
```

**Comment by linzhanglong** [comment]
I retested by unmapping a LUN, and this is the uevent event for the unmapping. My previous environment had 256 LUNs.
```
 # udevadm  monitor -k -p -s scsi
custom logging function 0x1fe6010 registered
selinux=0
runtime dir '/run/udev'
calling: monitor
monitor will print the received events for:
KERNEL - the kernel uevent

KERNEL[23808.067273] change   /devices/pci0000:3a/0000:3a:00.0/0000:3b:00.1/host15/rport-15:0-3/target15:0:2/15:0:2:1 (scsi)
ACTION=change
DEVPATH=/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.1/host15/rport-15:0-3/target15:0:2/15:0:2:1
DEVTYPE=scsi_device
DRIVER=sd
MODALIAS=scsi:t-0x00
SDEV_UA=REPORTED_LUNS_DATA_HAS_CHANGED
SEQNUM=19279
SUBSYSTEM=scsi
UDEV_LOG=6

KERNEL[23808.083982] change   /devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/host0/rport-0:0-4/target0:0:3/0:0:3:162 (scsi)
ACTION=change
DEVPATH=/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/host0/rport-0:0-4/target0:0:3/0:0:3:162
DEVTYPE=scsi_device
DRIVER=sd
MODALIAS=scsi:t-0x00
SDEV_UA=REPORTED_LUNS_DATA_HAS_CHANGED
SEQNUM=19281
SUBSYSTEM=scsi
UDEV_LOG=6

KERNEL[23808.098779] change   /devices/pci0000:3a/0000:3a:00.0/0000:3b:00.1/host15/rport-15:0-4/target15:0:3/15:0:3:1 (scsi)
ACTION=change
DEVPATH=/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.1/host15/rport-15:0-4/target15:0:3/15:0:3:1
DEVTYPE=scsi_device
DRIVER=sd
MODALIAS=scsi:t-0x00
SDEV_UA=REPORTED_LUNS_DATA_HAS_CHANGED
SEQNUM=19283
SUBSYSTEM=scsi
UDEV_LOG=6

KERNEL[23808.116540] change   /devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/host0/rport-0:0-9/target0:0:5/0:0:5:162 (scsi)
ACTION=change
DEVPATH=/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/host0/rport-0:0-9/target0:0:5/0:0:5:162
DEVTYPE=scsi_device
DRIVER=sd
MODALIAS=scsi:t-0x00
SDEV_UA=REPORTED_LUNS_DATA_HAS_CHANGED
SEQNUM=19285
SUBSYSTEM=scsi
UDEV_LOG=6

KERNEL[23808.131014] change   /devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/host0/rport-0:0-0/target0:0:0/0:0:0:1 (scsi)
ACTION=change
DEVPATH=/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/host0/rport-0:0-0/target0:0:0/0:0:0:1
DEVTYPE=scsi_device
DRIVER=sd
MODALIAS=scsi:t-0x00
SDEV_UA=REPORTED_LUNS_DATA_HAS_CHANGED
SEQNUM=19287
SUBSYSTEM=scsi
UDEV_LOG=6

KERNEL[23808.134275] change   /devices/pci0000:3a/0000:3a:00.0/0000:3b:00.1/host15/rport-15:0-9/target15:0:4/15:0:4:1 (scsi)
ACTION=change
DEVPATH=/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.1/host15/rport-15:0-9/target15:0:4/15:0:4:1
DEVTYPE=scsi_device
DRIVER=sd
MODALIAS=scsi:t-0x00
SDEV_UA=REPORTED_LUNS_DATA_HAS_CHANGED
SEQNUM=19289
SUBSYSTEM=scsi
UDEV_LOG=6

KERNEL[23808.149047] change   /devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/host0/rport-0:0-10/target0:0:4/0:0:4:1 (scsi)
ACTION=change
DEVPATH=/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/host0/rport-0:0-10/target0:0:4/0:0:4:1
DEVTYPE=scsi_device
DRIVER=sd
MODALIAS=scsi:t-0x00
SDEV_UA=REPORTED_LUNS_DATA_HAS_CHANGED
SEQNUM=19291
SUBSYSTEM=scsi
UDEV_LOG=6

KERNEL[23808.156474] change   /devices/pci0000:3a/0000:3a:00.0/0000:3b:00.1/host15/rport-15:0-12/target15:0:5/15:0:5:1 (scsi)
ACTION=change
DEVPATH=/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.1/host15/rport-15:0-12/target15:0:5/15:0:5:1
DEVTYPE=scsi_device
DRIVER=sd
MODALIAS=scsi:t-0x00
SDEV_UA=REPORTED_LUNS_DATA_HAS_CHANGED
SEQNUM=19293
SUBSYSTEM=scsi
UDEV_LOG=6

KERNEL[23808.160778] change   /devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/host0/rport-0:0-12/target0:0:6/0:0:6:1 (scsi)
ACTION=change
DEVPATH=/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/host0/rport-0:0-12/target0:0:6/0:0:6:1
DEVTYPE=scsi_device
DRIVER=sd
MODALIAS=scsi:t-0x00
SDEV_UA=REPORTED_LUNS_DATA_HAS_CHANGED
SEQNUM=19295
SUBSYSTEM=scsi
UDEV_LOG=6

KERNEL[23808.171297] change   /devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/host0/rport-0:0-13/target0:0:7/0:0:7:1 (scsi)
ACTION=change
DEVPATH=/devices/pci0000:3a/0000:3a:00.0/0000:3b:00.0/host0/rport-0:0-13/target0:0:7/0:0:7:1
DEVTYPE=scsi_device
DRIVER=sd
MODALIAS=scsi:t-0x00
SDEV_UA=REPORTED_LUNS_DATA_HAS_CHANGED
SEQNUM=19297
SUBSYSTEM=scsi
UDEV_LOG=6

KERNEL[23808.180670] change   /devices/pci0000:3a/0000:3a:00.0/0000:3b:00.1/host15/rport-15:0-10/target15:0:6/15:0:6:1 (scsi)
ACTION=change
DEVPATH=/devices
```

**Comment by linzhanglong** [comment]
I will merge the patch later today and test it in the environment with 256 LUNs.

**Comment by mwilck** [comment]
> I noticed that there are related operations for reload_and_sync_map at the end of the do_check_path function. Would it be more appropriate to reload the map there?

The `need_reload` flag is set in `update_pathvec_from_dm()`, which is called in the `update_multipath_strings()` code path. It makes sense to do the reload closely after that. `do_sync_mpp()` is where this check logically belongs [^fn]. The calls late in do_check_path() are meant to fix priorities.

However, I think now that calling `reload_and_sync_map()` in `do_sync_mpp()`, like in my path, is not ideal. We'll be pointlessly repeating ioctls. It's fine to test this I think I'll post an update to the patch.

[^fn]: We have lots of similar code paths for refreshing some properties of the maps either in multipathd or in the kernel, and that this is quite confusing even for people who've been working with this code base for years. Some day we'll need to clean this up.

**Comment by mwilck** [comment]
> However, I think now that calling reload_and_sync_map() in do_sync_mpp(), like in my path, is not ideal.

Indeed, this was wrong. `reload_and_sync_map()` may actually end up removing the map we're just working on.

I've pushed a new commit, 15747c2, that replaces the call to `reload_and_sync_map()` with one to just `reload_map()`. This is sufficient because we'll call `update_multipath_strings()` again in `do_sync_mpp()`.

@bmarzins, your feedback would be appreciated.

**Comment by mwilck** [comment]
Sorry for posting the wrong commit. 01ec4fa is correct.

**Comment by linzhanglong** [comment]
> Sorry for posting the wrong commit. [01ec4fa](https://github.com/opensvc/multipath-tools/commit/01ec4fa8657d222b484f89f4ccf65f0bf7903715) is correct.

Okay, I will test it.

**Comment by bmarzins** [comment]
Is there a big benefit to retrying immediately that I'm overlooking? Is this to deal with the case where reload_map() fails, or are you worried about successfully reloading the map, but having update_multipath_strings() still flag it as needing to be reloaded again? I seems to me that instead of immediately retrying, we could just wait till the next path check to try again.

Also, I think we do want to call reload_and_sync_map(). Right now, every call to domap() in multipathd will call setup_multipath() and sync_map_state() afterwards. I think we want to keep that for all cases. I posted a patchset that contains an alternate version of this patch.

**Comment by linzhanglong** [comment]
> Is there a big benefit to retrying immediately that I'm overlooking? Is this to deal with the case where reload_map() fails, or are you worried about successfully reloading the map, but having update_multipath_strings() still flag it as needing to be reloaded again? I seems to me that instead of immediately retrying, we could just wait till the next path check to try again.
> 
> Also, I think we do want to call reload_and_sync_map(). Right now, every call to domap() in multipathd will call setup_multipath() and sync_map_state() afterwards. I think we want to keep that for all cases. I posted a patchset that contains an alternate version of this patch.
Hello，regarding the patch set, where I can find it?

**Comment by mwilck** [comment]
> Is there a big benefit to retrying immediately that I'm overlooking?

In my mind, `need_reload` indicates an inconsistent state in the kernel. While we do our best to make sure that the kernel won't actually use this path for I/O, I think that we should attempt to fix this situation rather sooner than later.

**Comment by bmarzins** [comment]
@linzhanglong, the patches are available here:
https://lore.kernel.org/dm-devel/20241205035638.1218953-1-bmarzins@redhat.com/

**Comment by bmarzins** [comment]
> > Is there a big benefit to retrying immediately that I'm overlooking?
> 
> In my mind, `need_reload` indicates an inconsistent state in the kernel. While we do our best to make sure that the kernel won't actually use this path for I/O, I think that we should attempt to fix this situation rather sooner than later.

Sure, but is the retry for the case where the reload fails or where the reload succeeded, but the new table isn't right either? 

In my version of the patch, perhaps we could store a flag when `need_reload` is still set after the new call to reload_and_sync_map() in checkerloop, and cleared whenever the map is reloaded. Then we could check that flag and only require the `mpp->synced_count > 0` check if the last reload of the map was solely because of `need_reload`, and it didn't help.

That would make multipathd respond to a `need_reload` within a checker tick. If the reload didn't fix the problem, we would wait till the next time a path in the device is checked before trying again.

**Comment by mwilck** [comment]
I'd also prefer to do this kind of reload no more than once per tick.
But in your version of the patch, checkerloop() could release the lock before actually reloading the map after update_multipath_strings() detects an inconsistency. That sort of contradicts my "rather sooner than later" idea. I agree that possibly having to reload the map twice during a single tick is not beatiful, but given that such inconsistencies are very rare, IMO it shouldn't hurt much.

The idea of the retry was to check if update_pathvec_from_dm() still reports an inconsistency (which includes the case in which the reload failed, because in that case we'd have failed to fix the situation). I thought one immediate retry was warranted, given that this is a rare but serious error condition. But I've no idea about the likelihood that such an immediate retry would succeed.

I'll respond in the dm-devel thread.

**Comment by mwilck** [comment]
Another thought: we could attempt a single reload in `do_sync_mpp()` without an immediate retry (leaving `need_reload` set), and use your patch on top. This way if the reload in `do_sync_mpp()` failed, we'd retry at the end of the tick, with all path properties adjusted, which makes probably more sense than retrying immediately.

**Comment by bmarzins** [comment]
> I thought one immediate retry was warranted, given that this is a rare but serious error condition. But I've no idea about the likelihood that such an immediate retry would succeed.

But your code checks `retry++ < MAX_RETRIES` so that chunk will only run once and won't ever call reload_map() after jumping to try_again (retry will be 1 and MAX_RETRIES is 1). Even if `mpp->need_reload` gets set when it tries again, it will skip the code to reload the map. Right? That's what I didn't notice originally.

**Comment by mwilck** [comment]
Right, now **I** misinterpreted my own code :-)

Indeed the idea was just to retry reading the kernel parameters. I didn't intend to reload multiple times.

**Comment by mwilck** [comment]
My [tip branch](https://github.com/openSUSE/multipath-tools/tree/tip) now contains Ben's fixes plus an improved version of mine above, plus some cleanup.

@linzhanglong, Please provide feedback.

**Comment by linzhanglong** [comment]
> > 
> 
> Okay, I will test
I have merged the changes from this patch into the test environment without any issues. If there are any new changes, I will merge and test them today.

**Comment by linzhanglong** [comment]
> > Sorry for posting the wrong commit. [01ec4fa](https://github.com/opensvc/multipath-tools/commit/01ec4fa8657d222b484f89f4ccf65f0bf7903715) is correct.
> 
> Okay, I will test the new patch.

I have merged the changes from this patch into the test environment without any issues. If there are any new changes, I will merge and test them today.

**Comment by linzhanglong** [comment]
Test Okay

**Comment by linzhanglong** [comment]
Hello, when will the new version be released?  Is the branch at https://github.com/openSUSE/multipath-tools/tree/tip the next version?
