### ISSUE TITLE
Create team?

### ISSUE THREAD

**Issue by mwilck** [opensvc/multipath-tools#14]
@cvaroqui, I wonder if it would make sense to create a team for multipath-tools. Suggested members for a start would be you, @bmarzins, @xosevp, and myself. By allowing team members e.g. to close issues, yout could take some burden off yourself.

**Comment by cvaroqui** [comment]
Can you audit the team configuration i set up ?

**Comment by mwilck** [comment]
So you added myself, and granted "Triage" permissions on the multipath-tools repository. This looks good to me (thanks!), but I'd suggest inviting at least  Ben, too.

**Comment by cvaroqui** [comment]
Actually invites to xose and Ben were already sent  but in pending status when I asked you to audit. Since, xose has accepted the invitation, and Ben is still pending... All good, thank you for the confirmation.

**Comment by mwilck** [comment]
Thanks again. We'll notify you if we encounter any issues :-)

**Comment by mwilck** [comment]
Closing.
