### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by morrychan** [opensvc/multipath-tools#5]
when i make the project , i meet an error "main.cc:3063 error: implicit declaration of function rcu_barrier"，i use userspace-rcu-devel.x86_64(0.7.16-1.el7 ).it has no declaration of func rcu_barrier() in header urcu.h.anybody can help,please!

**Comment by morrychan** [comment]
> when i make the project , i meet an error "main.cc:3063 error: implicit declaration of function rcu_barrier"，i use userspace-rcu-devel.x86_64(0.7.16-1.el7 ).it has no declaration of func rcu_barrier() in header urcu.h.anybody can help,please!

which version of userspace-rcu-devel lib should i use?

**Comment by mwilck** [comment]
`rcu_barrier()` was added in user-space rcu 0.8.0. Calling it is a safety measure to make sure no RCU calls are underway when we detach the RCU thread. I think could simply remove that line / comment it out. Try running "multipathd reconfigure" and stopping/killing multipathd quickly after that to test whether you see any issues.

**Comment by mwilck** [comment]
The risk of deleting the rcu_barrier() call is pretty small. Unless I'm mistaken, at worst you'd have a minor memory leak on exit. But User-space RCU is subtle and not easy to understand, so to be on the safe side, I'm asking the liburcu developers if that call could be safely skipped in general.

**Comment by morrychan** [comment]
> `rcu_barrier()` was added in user-space rcu 0.8.0. Calling it is a safety measure to make sure no RCU calls are underway when we detach the RCU thread. I think could simply remove that line / comment it out. Try running "multipathd reconfigure" and stopping/killing multipathd quickly after that to test whether you see any issues.



> `rcu_barrier()` was added in user-space rcu 0.8.0. Calling it is a safety measure to make sure no RCU calls are underway when we detach the RCU thread. I think could simply remove that line / comment it out. Try running "multipathd reconfigure" and stopping/killing multipathd quickly after that to test whether you see any issues.

appreciate your reply，i will have a try

**Comment by morrychan** [comment]
> `rcu_barrier()` was added in user-space rcu 0.8.0. Calling it is a safety measure to make sure no RCU calls are underway when we detach the RCU thread. I think could simply remove that line / comment it out. Try running "multipathd reconfigure" and stopping/killing multipathd quickly after that to test whether you see any issues.

appreciate your reply，i will have a try，thanks again~

**Comment by morrychan** [comment]
> The risk of deleting the rcu_barrier() call is pretty small. Unless I'm mistaken, at worst you'd have a minor memory leak on exit. But User-space RCU is subtle and not easy to understand, so to be on the safe side, I'm asking the liburcu developers if that call could be safely skipped in general.

Please issue a commit if you have solved the problem，thanks  a lot ！

**Comment by morrychan** [comment]
> > `rcu_barrier()` was added in user-space rcu 0.8.0. Calling it is a safety measure to make sure no RCU calls are underway when we detach the RCU thread. I think could simply remove that line / comment it out. Try running "multipathd reconfigure" and stopping/killing multipathd quickly after that to test whether you see any issues.
> 
> appreciate your reply，i will have a try，thanks again~

it will be pretty nice if there has a README about how to deploy the system after making success

**Comment by mwilck** [comment]
> it will be pretty nice if there has a README about how to deploy the system after making success

You'd run `make install`. It's true that that isn't mentioned in the README; I suppose everyone just took it for granted the last 15 years. If you aren't familiar with this, you'll probably be better off just installing just a precompiled package, which is available on most Linux distributions. I would actually recommend that because multipath-tools is tightly bound to the distribution's device detection and boot logic, and different distributions do that in different ways. If you switch to self-compiled multipath-tools without knowing exactly what you're doing, you  are likely to experience boot issues.

Anyway, that request has nothing to do with the original issue you had. Please close it again.

**Comment by mwilck** [comment]
FTR: [user-space RCU discussion](https://lists.lttng.org/pipermail/lttng-dev/2021-May/029958.html)

**Comment by mwilck** [comment]
Proposed fix: 230e9ce

**Comment by mwilck** [comment]
Commit f441124 is now in the [queue](https://github.com/openSUSE/multipath-tools/tree/queue) branch. @morrychan, please try it.
