### ISSUE TITLE
multipathd started leads to initrd blocked.

### ISSUE THREAD

**Issue by lixiaokeng** [opensvc/multipath-tools#65]
With 11f0440 commit, we meet a problem.

When there is a multipath device in initrd, multipathd will be actived becasue of dracut/modules.d/90multipath/multipathd-needshutdown.sh running. This lead to  initrd-cleanup.service can't be run and switch root fails. The initrd is blocked.

https://github.com/dracutdevs/dracut/issues/2289

**Comment by mwilck** [comment]
I think the entire `multipathd-needshutdown.sh` logic is obsoleted by our `queue_without_daemon` feature. multipathd itself will take care that queuing is disabled when it quits.

@bmarzins, please double-check, I tend to overlook things lately ...

**Comment by mwilck** [comment]
If we still need `multipathd-needshutdown.sh` and `multipathd-shutdown.sh` (as noted above, I think we don't),
we should call multipath with the `-D` option in these files.

**Comment by mwilck** [comment]
@lixiaokeng, please try if removing the line
```
Also=multipathd.socket
```
in `multipathd.service` fixes the issue.

**Comment by lixiaokeng** [comment]
We test this （https://github.com/dracutdevs/dracut/pull/2290/files），and it fix this issue.

**Comment by lixiaokeng** [comment]
close
