### ISSUE TITLE
Build fails with `devmapper.c:387:97: error: unused parameter ‘deferred_remove’ [-Werror=unused-parameter]`

### ISSUE THREAD

**Issue by paulmenzel** [opensvc/multipath-tools#7]
Build version 0.8.6 fails with the error below:

```
$ make
[…]
cc --std=gnu99  -O2 -g -fstack-protector-strong --param=ssp-buffer-size=4 -Werror -Wall -Wextra -Wformat=2 -Werror=implicit-int -Werror=implicit-function-declaration -Werror=format-security -Wno-clobbered -Wno-error=clobbered -Werror=cast-qual -Werror=discarded-qualifiers -pipe -DBIN_DIR=\"/sbin\" -DLIB_STRING=\"lib64\" -DRUN_DIR=\"run\" -MMD -MP -fPIC -I../libmpathcmd -I../libmpathpersist -I../libmultipath/nvme -DUSE_SYSTEMD=242 -DLIBDM_API_FLUSH -D_GNU_SOURCE -DLIBDM_API_COOKIE -DLIBUDEV_API_RECVBUF -Wp,-D_FORTIFY_SOURCE=2  -c -o devmapper.o devmapper.c
devmapper.c: In function ‘dm_simplecmd’:
devmapper.c:387:97: error: unused parameter ‘deferred_remove’ [-Werror=unused-parameter]
  387 | dm_simplecmd (int task, const char *name, int no_flush, int need_sync, uint16_t udev_flags, int deferred_remove) {
      |                                                                                             ~~~~^~~~~~~~~~~~~~~
devmapper.c: In function ‘dm_flush_map_nopaths’:
devmapper.c:1125:48: error: unused parameter ‘deferred_remove’ [-Werror=unused-parameter]
 1125 | dm_flush_map_nopaths(const char * mapname, int deferred_remove)
      |                                            ~~~~^~~~~~~~~~~~~~~
devmapper.c: In function ‘dm_cancel_deferred_remove’:
devmapper.c:1576:46: error: unused parameter ‘mpp’ [-Werror=unused-parameter]
 1576 | dm_cancel_deferred_remove (struct multipath *mpp)
      |                            ~~~~~~~~~~~~~~~~~~^~~
```

**Comment by mwilck** [comment]
Interesting ... what distro / compiler are you using?

**Comment by paulmenzel** [comment]
We have our own distribution based loosely on Linux From Scratch ([MarIuX64](http://mariux64.molgen.mpg.de/)).

I tested GCC 7.5 and 10.1.

**Comment by mwilck** [comment]
asking because we are testing quite a few compilers in our github worklflows. Still not covering everything, obviously.

**Comment by mwilck** [comment]
OK - it's because you don't have LIBDM_API_DEFERRED set. You seem to be using a very old version of libdevmapper.

**Comment by paulmenzel** [comment]
Indeed, `/usr/include/libdevmapper.h` is from *lvm2-2.02.100-0.x86_64*.

**Comment by mwilck** [comment]
I'll create a patch to avoid this error. Be advised though that multipath testing has almost exclusively been done with newer versions of libdevmapper for several years. Maybe it's time to update :-)

**Comment by paulmenzel** [comment]
Thank you for your analysis and help.

Indeed, updating is a good idea. I only need `kpartx` and will run it manually.

**Comment by mwilck** [comment]
The easiest workaround in cases like this is to just using somewhat less strict warning flags. You could simply add -Wno-unused in the `WARNFLAGS` (`Makefile.inc`), for example. If you examine the warnings, you'll see that they are non-fatal, so loosening the flags a bit is justified for that specific use case. We are trying to use strict warn flags to catch errors, but making that work for any distro (or like in your case, with any old library version) is almost impossible, and thus we focus on more modern distros. Our CI goes back to Debian "Jessie", but we can't cover everything.

**Comment by mwilck** [comment]
Please test with 20c2697.

**Comment by paulmenzel** [comment]
Perfect. Tested successfully.

(In the commit message, you might want to prefix the issue URL with *Resolves:*. (But maybe you waited for my test.))

Thank you very much.

**Comment by mwilck** [comment]
Commit msg updated.

**Comment by mwilck** [comment]
I took the liberty to also add a Tested-by: Paul Menzel tag.

**Comment by paulmenzel** [comment]
Yes, thank you. I received your [patch message](https://lore.kernel.org/dm-devel/20210520195208.30542-1-mwilck@suse.com/T/#u).

**Comment by xosevp** [comment]
> Indeed, `/usr/include/libdevmapper.h` is from _lvm2-2.02.100-0.x86_64_.

It's nearly 8 years old !!!

You are going to find a lot of ~~bugs~~ fun.

**Comment by mwilck** [comment]
Well, at least code wise, we still support these old versions. We just haven't tested current multipath-tools on them for a long time. Also, there are enterprise distros released in 2014 which still have some years of support left. So, I'm generally glad about bug reports like this.
