### ISSUE TITLE
Question about mpathpersist?

### ISSUE THREAD

**Issue by lixiaokeng** [opensvc/multipath-tools#71]
Here we meet a problem. When we register a prkey（dm has 2 paths）, the mpathpersist is block 5s. The reason is that the second path request will come in storage server handling the first path. This will lead the second request come into waiting(5s) and retry process.  If the second request comes after first that finshing, it can be handled correctly. 
Here we found that registration is asynchronous, while reservation is synchronous. Why they are different?

**Comment by mwilck** [comment]
Can you please attach logs generated with `verbosity 4` to illustrate what you mean?

**Comment by lixiaokeng** [comment]
The current problem should be a compatibility issue between multipath services and storage services.
In some distributed storage services, it can not process two registration requests at the same time.  If two request arrives at the primary storage server almost simultaneously，the second request will be returned to the backup storage server and waited for 5 seconds on the backup service because primary storage server is dealing the first request . The reason of two request arriving at same time is that mpath_prout_reg creates two threads to send io. So I want to know why registration is asynchronous？ If we finish first one request then send second request, the primary storage server can handle it correctly。

**Comment by mwilck** [comment]
Thanks for the explanantion. I'd still like to see some logs, it's difficult to get a clear idea of what's happening just from the high-level description.

**Comment by lixiaokeng** [comment]
Sdii is finished immediately, but sdij and sdih waited for 5 seconds.

**Comment by mwilck** [comment]
Hm. What exactly could multipathd do differently here?

**Comment by lixiaokeng** [comment]
Because registration will change the metadata of the lun, the primary storage server will lock and it can't deal with two or more request at the same time. There is no queue in  the primary storage, so it will send the second request to  backup storage server and enter waiting mode（5s）.   To be honest, I am not familiar with this storage either. This is what the person in charge of the storage told me. I have the same question.  Why did they design it this way?
Maybe this question is the storage needs to think about the solution to this problem but not multipath-tools. Because we don't meet this question in other storage.

**Comment by mwilck** [comment]
Well this makes a certain amount of sense, although we've never seen this behavior before.

Can you find out what exactly the restriction is? I.e., can the entire storage unit only process one STPG at a time? Or only one STPG per port / LUN / ..., whatever?

**Comment by lixiaokeng** [comment]
I can't get more information. Sorry.
Maybe this issue could be close.
