### ISSUE TITLE
nvme enable Integrity check，host crash.

### ISSUE THREAD

**Issue by Passion1121** [opensvc/multipath-tools#90]
when nvme device enable integrity check，If the connection is disconnected during the io process, the host will crash。I checked and found that it was caused during the reload map. Is there any way to avoid it? Of course, I think it's not just nvme that has this problem.
kernel version: 4.18.0-348.el8.x86_64
multipath version: 0.9.9

![image](https://github.com/opensvc/multipath-tools/assets/45610911/5c5ac088-f95b-42ed-98ff-bf2ccf1070f0)

**Comment by mwilck** [comment]
This has nothing to do with multipath-tools. It's a problem of the Red Hat kernel. Please report to Red Hat.

**Comment by Passion1121** [comment]
ok，thanks！
